server:
  port: 8081

# Database
spring:
  datasource:
    url: jdbc:h2:mem:library_db
    username: user
    password: SecretPassword
    driver-class-name: org.h2.Driver

# Application env
application:
  issue:
    max-allowed-books: 3

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs
